config/routes.rb
Rails.application.routes.draw do
  resources :events do 
    member do 
      post 'deactivate_event'
      post 'add_comment'
    end     
  end
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event , optional: true 
  validates_presence_of :comment
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user , optional: true 
  validates :title, :description , :start_date , :end_date ,:begin_time,:end_time, presence: true
  validates :location, :entry_type , :contact_person , :mobile_number,:event_category, presence: true
  validates_length_of :title, :minimum => 10, :maximum => 30, :allow_blank => true
  validates_length_of :description, :minimum => 10, :maximum => 1000, :allow_blank => true
  validate :valid_date_range_required
  validate :valid_event_time
  has_many :comments
  
  def valid_date_range_required
    if (start_date && end_date) && (start_date > end_date)
      errors.add(:start_date, "must be less than end_date")
    end
  end  
  def valid_event_time
    if (begin_time && end_time) && (begin_time > end_time)
      errors.add(:begin_time, "must be less than end_time")
    end
  end    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
  validates_presence_of :first_name , :last_name
  def name
    return "#{self.first_name} #{self.last_name}"
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy,:add_comment]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  def add_comment
    @comment =  Comment.new(comment_params)
    if @comment.save 
      redirect_to @event , notice: 'Comment added successfuly'
    else
        redirect_to @event , notice: 'unable to add comment'
    end
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def deactivate_event
    @event = Event.find(params[:id])
    if @event and @event.status == 'Published'
      @event.update_attributes(status: 'InActive')
      redirect_to events_url, notice: 'Your Event was successfully published.'
    else
      redirect_to events_url, notice: 'Your Request cannot be published.'
    end 
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
    def comment_params
      params.require(:comment).permit(:comment,:user_id ,:event_id)
    end 
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date, :begin_time, :end_time, :location, :entry_type, :hosted_by, :contact_person, :contact_email, :mobile_number, :chief_guest, :status, :event_category, :user_id)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role_id)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password,:role_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, :html => { :role => 'form'}) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form.hidden_field :user_id, value: current_user.id  %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= form.label :event_category %>
    <%= form.select :event_category, options_for_select(CATEGORY_TYPES,@event.event_category), {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :begin_time %>
    <%= form.time_select :begin_time, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :end_time %>
    <%= form.time_select :end_time, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_area :location, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :entry_type %>
    <%= form.select :entry_type, options_for_select(ENTRY_TYPES,@event.entry_type), {}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :hosted_by %>
    <%= form.text_field :hosted_by, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :contact_person %>
    <%= form.text_field :contact_person, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :contact_email %>
    <%= form.email_field :contact_email, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :mobile_number %>
    <%= form.text_field :mobile_number, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :chief_guest %>
    <%= form.text_field :chief_guest, class: 'form-control'  %>
  </div>




  <div class="actions">
    <%= form.submit :class => 'btn btn-primary right' %>
  </div>
<% end %>
<br/>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Events</h1>
<% if !@events.blank? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Entry type</th>
      <th>Status</th>
      <th>Event category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.location %></td>
        <td><%= event.entry_type %></td>
        <td><%= event.status %></td>
        <td><%= event.event_category %></td>
        <td><%= link_to 'Show', event %></td>
        <% if event.user == current_user %>
          <td><%= link_to 'Edit', edit_event_path(event)  %></td>
           <td> <%= link_to 'Make InActive' ,deactivate_event_event_path(event),method: 'post' ,data:{confirm: "Are you sure? Want to in-activate it ?"} if event.status== 'Published' %>
          </td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } if event.user == current_user%></td>        
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<p>No Events</p>
<% end %>
<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Begin time:</strong>
  <%= @event.begin_time.strftime("%H:%M %P") %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time.strftime("%H:%M %P") %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Entry type:</strong>
  <%= @event.entry_type %>
</p>

<p>
  <strong>Hosted by:</strong>
  <%= @event.hosted_by %>
</p>

<p>
  <strong>Contact person:</strong>
  <%= @event.contact_person %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @event.contact_email %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @event.mobile_number %>
</p>

<p>
  <strong>Chief guest:</strong>
  <%= @event.chief_guest %>
</p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<p>
  <strong>Event category:</strong>
  <%= @event.event_category %>
</p>


<h2>  Comments</h2>

<%= form_for(:comment,  url: add_comment_event_path, html: { role: 'form'}) do |f| %>
  <%= f.hidden_field :user_id , class: 'form-control' , value: current_user.id%>
  <%= f.hidden_field :event_id , class: 'form-control' , value: @event.id%>
  <p>Comment: </p>
  <%= f.text_area :comment , class: 'form-control' , required: true %>
  <%= f.submit "Comment" %>
<% end %>
<hr>
 <% @event.comments.each do |c| %>
 <p><%= c.comment %></p>
 <% end %>
 <br/>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Events', events_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <%= link_to "Rails Rspec", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button> 
  <div class="collapse navbar-collapse" id="collapsibleNavbar">   
      <ul class="nav navbar-nav ml-auto">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Rspec" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Rspec" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>